[package]
name = "quotes"
version = "0.1.0"
authors = ["oabrivard <olivier@abrivard.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
